In [1]:
# USAGE
# python grabcut_bbox.py
# import the necessary packages
import numpy as np
import argparse
import time
from PIL import Image
import cv2
#import os



# load the input image from disk and then allocate memory for the
# output mask generated by GrabCut -- this mask should hae the same
# spatial dimensions as the input image
image = cv2.imread('bird.jpg')
mask = np.zeros(image.shape[:2], dtype="uint8")

# define the bounding box coordinates
#140,396 height 10,285
#227,772 height 77,646
rect = (227, 77,772, 646)

# allocate memory for two arrays that the GrabCut algorithm internally
# uses when segmenting the foreground from the background
fgModel = np.zeros((1, 65), dtype="float")
bgModel = np.zeros((1, 65), dtype="float")

# apply GrabCut using the the bounding box segmentation method
start = time.time()
print('started')
(mask, bgModel, fgModel) = cv2.grabCut(image, mask, rect, bgModel,
	fgModel, iterCount=10, mode=cv2.GC_INIT_WITH_RECT)
print('ended')
end = time.time()
print("[INFO] applying GrabCut took {:.2f} seconds".format(end - start))

# the output mask has for possible output values, marking each pixel
# in the mask as (1) definite background, (2) definite foreground,
# (3) probable background, and (4) probable foreground
values = (
	("Definite Background", cv2.GC_BGD),
	("Probable Background", cv2.GC_PR_BGD),
	("Definite Foreground", cv2.GC_FGD),
	("Probable Foreground", cv2.GC_PR_FGD),
)

# loop over the possible GrabCut mask values
for (name, value) in values:
	# construct a mask that for the current value
	print("[INFO] showing mask for '{}'".format(name))
	valueMask = (mask == value).astype("uint8") * 255

	# display the mask so we can visualize it
	#cv2.imshow(name, valueMask)
	#cv2.waitKey(0)

# we'll set all definite background and probable background pixels
# to 0 while definite foreground and probable foreground pixels are
# set to 1
outputMask = np.where((mask == cv2.GC_BGD) | (mask == cv2.GC_PR_BGD),
	0, 1)


# scale the mask from the range [0, 1] to [0, 255]
outputMask = (outputMask * 255).astype("uint8")
print(outputMask)
im1 = Image.fromarray(outputMask)
im1 = im1.save('frst2.jpg')

# apply a bitwise AND to the image using our mask generated by
# GrabCut to generate our final output image
output = cv2.bitwise_and(image, image, mask=outputMask)

# show the input image followed by the mask and output generated by
# GrabCut and bitwise masking
#cv2.imshow("Input", image)
#cv2.imshow("GrabCut Mask", outputMask)
#cv2.imshow("GrabCut Output", output)
#cv2.waitKey(0)
im1 = Image.fromarray(output)
im1 = im1.save('out2.jpg')


started
ended
[INFO] applying GrabCut took 5.65 seconds
[INFO] showing mask for 'Definite Background'
[INFO] showing mask for 'Probable Background'
[INFO] showing mask for 'Definite Foreground'
[INFO] showing mask for 'Probable Foreground'
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [2]:
im1=Image.open('frst2.jpg')
im1=np.array(im1)
print(im1.shape)
se= np.unique(im1)
print(se)
im1r=np.zeros([im1.shape[0],im1.shape[1]])
for i in range(im1.shape[0]):
    for j in range(im1.shape[1]):
        im1r[i,j]=255-im1[i,j]
im2=Image.fromarray(im1r.astype(np.uint8))
im2.save('birdb.jpg')
print(im1r)
            

(732, 1100)
[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  43 216 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232
 233 234 235 236 237 238 239 240 241 242 243 244 245 246 247 248 249 250
 251 252 253 254 255]
[[255. 255. 255. ... 255. 255. 255.]
 [255. 255. 255. ... 255. 255. 255.]
 [255. 255. 255. ... 255. 255. 255.]
 ...
 [255. 255. 255. ... 255. 255. 255.]
 [255. 255. 255. ... 255. 255. 255.]
 [255. 255. 255. ... 255. 255. 255.]]


In [3]:
im1=Image.open('birdb.jpg')
im1=np.array(im1)
im2=Image.open('flower.jpg')
im2=np.array(im2)
mask=Image.open('flob.jpg')
mask=np.array(mask)
#im = Image.composite(im2, im1, mask)
res=cv2.bitwise_and(im2, im2, mask=mask)
print(res)
im=Image.fromarray(res)
im.save('floob.jpg')
# im = Image.blend(im1, im2, 0.5)

[[[19 25 11]
  [19 25 11]
  [22 26 12]
  ...
  [32 46 10]
  [31 45  9]
  [32 48 11]]

 [[18 24 10]
  [18 24 10]
  [21 25 11]
  ...
  [32 46 10]
  [32 46 10]
  [30 46  9]]

 [[16 24  9]
  [17 23  9]
  [18 24 10]
  ...
  [33 47 11]
  [33 47 11]
  [29 45  8]]

 ...

 [[37 49 27]
  [39 51 29]
  [44 53 32]
  ...
  [31 38  5]
  [30 40  6]
  [28 39  5]]

 [[37 49 27]
  [39 51 29]
  [44 53 32]
  ...
  [31 38  5]
  [30 40  6]
  [28 39  5]]

 [[37 49 27]
  [39 51 29]
  [44 53 32]
  ...
  [29 39  5]
  [29 40  6]
  [28 39  5]]]
