In [1]:
import numpy as np
import scipy
from numpy.linalg import eig
from scipy.linalg import det

In [15]:
def mySVD(A):
  m,n = A.shape

  M = np.matmul(A,A.T)
  eig_values_M, U = eig(M)

  sorted_indices_M = np.flip(eig_values_M.argsort())

  eig_values_M = eig_values_M[sorted_indices_M]
  U = U[:,sorted_indices_M]

  V = np.matmul(A.T,U)
  V_norms = np.linalg.norm(V,axis=0)
  V = V/V_norms

  S = np.diag(np.abs(np.sqrt(eig_values_M)))

  return U,S,V

In [26]:
A = np.random.rand(3,5)

print("Original Matrix \n",A,"\n")

U,S,V = mySVD(A)

US = np.matmul(U,S)
USV = np.matmul(US,V.T)

print("Reconstructed Matrix \n",USV,"\n")

print("Frobenian Error =",np.linalg.norm(A-USV))

Original Matrix 
 [[0.62769402 0.35625672 0.04379014 0.90937452 0.43695893]
 [0.24623799 0.16417425 0.13077553 0.68796705 0.7460456 ]
 [0.2261798  0.69345143 0.63095313 0.01635929 0.66683978]] 

Reconstructed Matrix 
 [[0.62769402 0.35625672 0.04379014 0.90937452 0.43695893]
 [0.24623799 0.16417425 0.13077553 0.68796705 0.7460456 ]
 [0.2261798  0.69345143 0.63095313 0.01635929 0.66683978]] 

Frobenian Error = 8.32117758046192e-16


In [ ]:
#This method doesn't work always
def mySVD(A):
  m,n = A.shape
  r = min(m,n)

  M = np.matmul(A,A.T)
  N = np.matmul(A.T,A)

  eig_values_M, U = eig(M)
  eig_values_N, V = eig(N)

  sorted_indices_M = np.flip(eig_values_M.argsort())
  sorted_indices_N = np.flip(eig_values_N.argsort())

  eig_values_M = eig_values_M[sorted_indices_M]
  U = U[:,sorted_indices_M]
  eig_values_N = eig_values_N[sorted_indices_N]
  V = V[:,sorted_indices_N]

  S_int = np.diag(np.abs(np.sqrt(eig_values_M[:r])))
  S = np.zeros((m,n))
  S[:r,:r] = S_int

  return U,S,V